apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: block-external-network
spec:
  action: partition # the specific chaos action to inject
  mode: one # the mode to run chaos action; supported modes are one/all/fixed/fixed-percent/random-max-percent
  selector: # pods where to inject chaos actions
    namespaces:
      - default
    labelSelectors:
      "app": "jfrcosmos"
  direction: to
  externalTargets:
    - "REDACTED.documents.azure.com"
  delay:
    latency: "2000ms"
  duration: "15s" # duration for the injected chaos experiment
  scheduler: # scheduler rules for the running time of the chaos experiments about pods.
    cron: "@every 15s"