# Default values for jmetertestrig.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
Globals:
  RedisEnabled: true
replicaCount: 2
jmeterMasterImage: shadowpic/jmeter-master:latest
jmeterMasterMemory: 4Gi
jmeterMasterCpu: 2
jmeterSlaveMemory: 2Gi
jmeterSlaveCpu: 2
jmeterSlaveImage: shadowpic/jmeter-slave:latest
jmeterInfluxDbImage: influxdb:1.8
jmeterInfluxDbStorageClass:  # Allow specifying alternate StorageClass
csv2RedisEnabled: true
csv2RedisImage: shadowpic/csv2redis:latest
influxDBEnabled: true
redis:
  usePassword: false
  cluster:
    enabled: false
