# Default values for jmetertestrig.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
jmeterMasterImage: shadowpic/jmeter-master:latest
jmeterSlaveImage: shadowpic/jmeter-slave:latest
jmeterInfluxDbImage: influxdb:1.8
jmeterInfluxDbStorageClass:  # Allow specifying alternate StorageClass
redis:
  usePassword: false
  cluster:
    enabled: false