apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      jmeter_mode: slave
    name: {{ template "fullname" . }}-jmeter-slaves
  spec:
    progressDeadlineSeconds: 600
    replicas: {{ .Values.replicaCount }}
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        jmeter_mode: slave
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          jmeter_mode: slave
          chart: {{ template "name" . }}
          release: {{ .Release.Name }}
      spec:
        containers:
        - args:
          - -Dserver.rmi.ssl.disable=true
          - -Djava.rmi.server.hostname=$(MY_POD_IP)
          - -Dserver.rmi.localport=50000
          - -Dserver_port=1099
          command:
          - /jmeter/apache-jmeter-$(JMETER_VERSION)/bin/jmeter-server
          env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: JMETER_VERSION
            value: "5.4.3"
          image: {{ .Values.jmeterSlaveImage }}
          imagePullPolicy: Always
          name: jmslave
          ports:
          - containerPort: 1099
            protocol: TCP
          - containerPort: 50000
            protocol: TCP
          resources:
            limits:
              cpu: "{{ .Values.jmeterSlaveCpu }}"
              memory: "{{ .Values.jmeterSlaveMemory }}"
            requests:
              cpu: ".5"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 10
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      jmeter_mode: slave
      chart: {{ template "name" . }}
      release: {{ .Release.Name }}
    name: jmeter-slaves-svc
  spec:
    clusterIP: None
    ports:
    - name: first
      port: 1099
      protocol: TCP
      targetPort: 1099
    - name: second
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      jmeter_mode: slave
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
